---
title: "Creating a Treemap"
author: "Hanna"
date: '2022-12-02'
output:
  pdf_document: default
layout: post
tags: github datavis
meta: Tutorials
---



<div class="block">
	


</div>

## Tutorial Aims:
#### 1.Develop a good understanding of Treemaps and how they are useful 
#### 2.Understand how to upload data into your R Studio 
#### 3.Be able to transform data into a Treemap
#### 4.Be able to change the appearance of a Treemap 

## Steps: 

#### <a href="#packages"> 1. Loading needed packages </a>

#### <a href="#data"> 2. Downloading data</a>

#### <a href=”#plot”> 3. Creating the Treemap</a>

#### <a href=”#change”> 4. Changing your Treemaps look</a> 

#### <a href=”#inter”> 5. Making your Treemap more interactive</a> 

#### <a href=”#more”> 6. More sources</a> 

## What is a Treemap?

In its most basic form, a Treemap is used to visualize proportions. Similar to a pie chart, a Treemap allows the reader to see different values as part of a whole, in this case a large rectangle instead of a circle. Treemaps are also super useful to display lots of information in a small amount of space. Using hierarchical Treemaps allow the plot to interactive and show different kinds of information. 

Treemaps can come in multiple forms ranging from very basic to very complex. Today you will be learning the most basic kind of Treemap and how to make it interactive. 



<a name="packages"></a>

## 1. Loading needed packages


For this tutorial you will need 5 different packages. Copy the code below into your RStudio and run it to install and load the needed package. 



`install.packages("tidyverse")`

`install.packages("treemap")`

`install.packages("dplyr")`


`install.packages("readr")`


`install.packages("d3treeR")`


`devtools::install_github("timelyportfolio/d3treeR") # use this code if d3treeR does not install on the first try (remove the # to run this code)
`


Once you have installed these packages it is time to load them up. Use the code below to do that. 


`library(tidyverse)`

`library(treemap)`

`library(dplyr)`

`library(readr)`

`library(d3treeR)`



<a name="data"></a>

## 2. Downloading data

To get the needed data, please visit this repository. Once you have copied the repo, please set your working directory to where you saved it on your device. Use the following code to set your working directory.


`setwd("You_file_path")`

The next step in this process is to load the data from the repo and view it in your RStudio. Use the code below to do that. 

`popdata <- read.csv("us_pop_by_state.csv")` 

`view(popdata)` 

An important thing to keep in mind if you decide to make a Treemap with your own data is to make sure your data is compatable. To make a Treemap you need to have data that has a numberic, usually continuous, value and 


<a name="plot"></a>

## 3. Creating the Treemap 


<a name="change"></a>

## 4. Changing your Treemaps look 


<a name="inter"></a>

## 5. Making your Treemap interactive


<a name="more"></a>

## Learn more with these sources!


